### ISSUE TITLE
unable to get traffic to WAN

### ISSUE THREAD

**Issue by biax** [didenko/er_poe_fw#1]
```
set firewall name GUEST_IN default-action drop
set firewall name GUEST_IN description 'GUEST in'
set firewall name GUEST_IN rule 1 action accept
set firewall name GUEST_IN rule 1 description 'Allow established/related'
set firewall name GUEST_IN rule 1 state established enable
set firewall name GUEST_IN rule 1 state related enable
set firewall name GUEST_IN rule 2 action drop
set firewall name GUEST_IN rule 2 description 'Drop invalid state'
set firewall name GUEST_IN rule 2 state invalid enable
set firewall name GUEST_IN rule 3 action accept
set firewall name GUEST_IN rule 3 description 'GUEST new to WAN'
set firewall name GUEST_IN rule 3 state new enable
set firewall name GUEST_IN rule 3 destination group address-group ADDRv4_eth0
```

thats an adaptation of your script. im unable to ping from GUEST network to WAN. i was hoping to use your version as its cleaner but i had to settle for this:

default accept
accept est/rel
drop invalid
drop rfc1918 lan subnets

i dont quite like this.. so i hope you can tell me how to make your version work. i have also tried using interface-network instead of address-group

**Comment by didenko** [comment]
@biax, I am not sure how to address your issue. There is just too much context needed to properly address the problem you are experiencing and I will not be able to provide the effort needed to dig into that context.

This  writeup is not intended to be a working script, but rather an illustration on a way of thinking. I am not a security expert so it would be very inappropriate for me to give any specific advise for a firewall configuration.

I am sorry I can not be of more help.
